name: MotoServer
main: com.mike724.motoserver.MotoServer
version: ${version}
authors: [Mike724, Dakota628]
commands:
   net:
      description: This is a network command.
      usage: /net [args...]
   addfriend:
      description: Add a friend your friends list.
      usage: /addfriend <name>
   delfriend:
      description: Delete a friend from your friends list.
      usage: /delfriend <name>
   setrank:
      description: Set a players rank on the network.
      usage: /setrank <name> <rank>
   cmdauth:
      description: Runs a command if the player has the desired auth
      usage: /cmdauth <player> <perms> <command>
   spawn:
      description: Teleport to the hub spawn.
      usage: /hub [player]